// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=pango/services/cellar/design
// --out=$(GOPATH)/src/pango/services/cellar
// --version=v1.3.1

package client
